import { useState } from "react";
const PK="#C2185B",PM="#E91E90",BG="#FDF2F8",PC="#FFF5FA",CD="#FFFFFF",DK="#2D2235",MD="#5C526A",GR="#9990A8",LT="#E8E0F0",WH="#FFFFFF";
const sc={name:"WMT Dough",cookiesPerCU:4,cuPerCase:12,cookiesPerCase:48,ti:9,hi:21,casesPerPallet:189};
const dotInv=[{sku:"WCCB",name:"Cookie Butter White Choc Chip",onHand:62196,incoming:5000,transit:8400,alloc:12000,vel:4800},{sku:"PBG",name:"Grape Jelly Stuffed PB",onHand:30060,incoming:0,transit:3600,alloc:6000,vel:3200}];
const products=[
  {sku:"C-F-SC-WCCB-12-12-WMT",short:"WCCB",name:"Cookie Butter Stuffed White Choc Chip",status:"active",launch:"2026-01-15",cog:2.00,rev:3.00,shelf:270,retailer:"Walmart"},
  {sku:"C-F-SC-WCCB-12-13-KF",short:"WCCB-KF",name:"Private Selection Cookie Butter White Choc Chip",status:"active",launch:"2026-03-01",cog:null,rev:31.20,shelf:270,retailer:"Kroger",note:"Kroger vendor item code. $31.20/cs Cortina cost."},
  {sku:"C-F-SC-PBG-12-12-WMT",short:"PBG",name:"Grape Jelly Stuffed Peanut Butter",status:"active",launch:"2026-01-15",cog:2.00,rev:3.00,shelf:270,retailer:"Walmart"},
  {sku:"C-F-SC-WCCB-8-12-WMT",short:"WCCB-8",name:"Cookie Butter White Choc Chip (8ct)",status:"upcoming",launch:"2026-07-14",cog:null,rev:null,shelf:270,retailer:"Walmart",transNote:"Spec change: 12ct to 8ct. New UPC."}
];
const rawMats=[
  {code:"111006",name:"Thermopure Flour",qty:95885,unit:"lbs",lots:3,exp:"Feb 2027",flag:"good",lead:14,
   distributors:[{dist:"St Charles",brand:"Ardent Mills",cost:0.28,moq:25000,lead:14},{dist:"Dawn",brand:"Gold Medal",cost:0.30,moq:20000,lead:10}],
   orders:[{d:"Mar 10",s:"Ardent Mills",dist:"St Charles",q:25885,c:0.28,src:"email"},{d:"Feb 20",s:"Ardent Mills",dist:"St Charles",q:30000,c:0.28,src:"email"}],
   fifo:[{lot:"FL-2401",q:40000,exp:"Feb 2027"},{lot:"FL-2402",q:30000,exp:"Feb 2027"},{lot:"FL-2403",q:25885,exp:"Feb 2027"}],
   usage:[{p:"WCCB",q:850},{p:"PBG",q:780}]},
  {code:"119002",name:"Light Brown Sugar",qty:45639,unit:"lbs",lots:4,exp:"Mixed",flag:"partial_expired",expQty:50,lead:7,
   distributors:[{dist:"St Charles",brand:"Domino",cost:0.42,moq:10000,lead:7},{dist:"Dawn",brand:"C&H",cost:0.44,moq:8000,lead:5}],
   orders:[],fifo:[{lot:"BS-001",q:50,exp:"EXPIRED"}],usage:[{p:"WCCB",q:320},{p:"PBG",q:280}]},
  {code:"112003",name:"Monila Vanilla",qty:41664,unit:"lbs",lots:28,exp:"Mixed",flag:"good",lead:21,
   distributors:[{dist:"St Charles",brand:"Monila Inc",cost:1.85,moq:5000,lead:21}],
   orders:[{d:"Mar 1",s:"Monila Inc",dist:"St Charles",q:20000,c:1.85,src:"email"}],fifo:[],usage:[{p:"WCCB",q:140}]},
  {code:"116053",name:"Grape Jelly",qty:27272,unit:"lbs",lots:2,exp:"Dec 2026",flag:"good",lead:10,
   distributors:[{dist:"Dawn",brand:"Smucker's",cost:0.95,moq:5000,lead:10}],
   orders:[],fifo:[],usage:[{p:"PBG",q:620}]},
  {code:"116065",name:"REESE'S PB Chips",qty:10386,unit:"lbs",lots:1,exp:"Jul 2026",flag:"almost_expired",lead:35,
   distributors:[{dist:"St Charles",brand:"REESE'S (Hershey's)",cost:3.40,moq:10000,lead:35},{dist:"Dawn",brand:"Barry Callebaut",cost:2.10,moq:15000,lead:28}],
   orders:[],fifo:[],usage:[]},
  {code:"111370",name:"DC Cookie Butter",qty:9166,unit:"lbs",lots:4,exp:"Nov 2026",flag:"good",lead:10,
   distributors:[{dist:"Internal",brand:"DC Homemade",cost:1.50,moq:0,lead:10}],
   orders:[],fifo:[],usage:[]},
  {code:"110014",name:"Eggs Liquid Whole",qty:7613,unit:"lbs",lots:3,exp:"May 2026",flag:"partial_expired",expQty:20,lead:3,
   distributors:[{dist:"Dawn",brand:"Michael Foods",cost:0.55,moq:2000,lead:3}],
   orders:[],fifo:[],usage:[]}
];
const packaging=[{code:"120001",name:"Trays",qty:2156558,unit:"units"},{code:"120003",name:"Film WCCB",qty:216711,unit:"units"},{code:"120004",name:"Film PBJ",qty:227500,unit:"units"},{code:"123001",name:"Master Cases",qty:10793,unit:"units"}];
const today=new Date(2026,4,20);
const POs=[
  {id:"PO14371",inv:"TBD",dt:"May 8",mabd:"May 28",dc:"Kroger DC Shelbyville IN",ship:"pending",pay:"pending",cs:504,em:2,origShip:"May 21",actShip:null,shipDt:new Date(2026,4,21),lines:[{sku:"WCCB-KF",qty:504}],payAmt:"$15,724.80",paidAmt:"$0",nova:null,ret:"Kroger",terms:"Due on receipt",revPerCs:31.20},
  {id:"PO14400",inv:"TBD",dt:"May 14",mabd:"Jun 3",dc:"Kroger DC Forest Park GA",ship:"pending",pay:"pending",cs:504,em:2,origShip:"May 27",actShip:null,shipDt:new Date(2026,4,27),lines:[{sku:"WCCB-KF",qty:504}],payAmt:"$15,724.80",paidAmt:"$0",nova:null,ret:"Kroger",terms:"Due on receipt",revPerCs:31.20},
  {id:"PO14326",inv:"INV-4326",dt:"Apr 23",mabd:"May 13",dc:"Walmart DC",ship:"shipped",pay:"pending",cs:720,em:7,origShip:"May 6",actShip:"Apr 29",carrier:"SunTeck TTS",freight:"Cortina",bol:true,ready:"Apr 27",shipDt:new Date(2026,3,29),lines:[{sku:"WCCB",qty:480},{sku:"PBG",qty:240}],payAmt:"$2,160",paidAmt:"$0",nova:"Ship date pulled forward May 6 to Apr 29",ret:"Walmart",terms:"Net 30/60",revPerCs:3.00},
  {id:"PO14331",inv:"INV-4331",dt:"Apr 24",mabd:"Apr 28",dc:"Walmart DC",ship:"delivered",pay:"paid_national",cs:480,em:2,turn:"3-day",origShip:"Apr 27",actShip:"Apr 27",shipDt:new Date(2026,3,27),lines:[{sku:"WCCB",qty:480}],payAmt:"$1,440",paidAmt:"$1,440",nova:null,ret:"Walmart",terms:"Net 30/60",revPerCs:3.00},
  {id:"PO14290",inv:"INV-4290",dt:"Apr 18",mabd:"May 9",dc:"DC #6057",ship:"delivered",pay:"paid_national",cs:960,em:3,shipDt:new Date(2026,3,20),lines:[{sku:"WCCB",qty:576},{sku:"PBG",qty:384}],payAmt:"$2,880",paidAmt:"$2,880",nova:null,ret:"Walmart",terms:"Net 30/60",revPerCs:3.00},
  {id:"PO14255",inv:"INV-4255",dt:"Apr 14",mabd:"May 2",dc:"DC #7022",ship:"delivered",pay:"paid_dc",cs:1440,em:5,shipDt:new Date(2026,3,16),lines:[{sku:"WCCB",qty:864},{sku:"PBG",qty:576}],payAmt:"$4,320",paidAmt:"$4,320",nova:"Qty adjusted from 1500 to 1440 via NOVA",ret:"Walmart",terms:"Net 30/60",revPerCs:3.00},
  {id:"PO14201",inv:"INV-4201",dt:"Apr 8",mabd:"Apr 28",dc:"DC #6057",ship:"delivered",pay:"awaiting_walmart",cs:720,em:4,shipDt:new Date(2026,3,10),lines:[{sku:"WCCB",qty:432},{sku:"PBG",qty:288}],payAmt:"$2,160",paidAmt:"$0",nova:null,ret:"Walmart",terms:"Net 30/60",revPerCs:3.00}
].sort((a,b)=>{const sa=a.ship==="pending"?0:a.ship==="shipped"?1:2;const sb=b.ship==="pending"?0:b.ship==="shipped"?1:2;if(sa!==sb) return sa-sb;return a.shipDt-b.shipDt;});
const daysTo=(d)=>{const diff=Math.ceil((d-today)/(1000*60*60*24));return diff;};
const emails14326=[{t:"Apr 23, 8:46 AM",f:"Noah LiDestri",r:"Cortina",a:"PO issued",x:{shipDate:"May 6"}},{t:"Apr 23, 11 AM",f:"Marc Bouthillette",r:"DC",a:"Ready, requests earlier ship",x:{readyDate:"Apr 27"}},{t:"Apr 24, 2:37 PM",f:"Marc",r:"DC",a:"Cortina handles freight",x:{freight:"Cortina"}},{t:"Apr 24, 9:38 PM",f:"Harshita Gedela",r:"Cortina",a:"Checking buyer",x:{revisedShip:"Apr 29"}},{t:"Apr 28, 3:32 PM",f:"Martin Gogoski",r:"SunTeck",a:"BOL attached",x:{carrier:"SunTeck TTS"}}];
const emails14371=[{t:"May 8, 11:03 AM",f:"Harshita Gedela",r:"Cortina",a:"PO issued. Kroger WCCB 504cs.",x:{shipDate:"May 21",dest:"Kroger Shelbyville IN",total:"$15,724.80"}},{t:"May 8, 12:40 PM",f:"Maria Restrepo",r:"DC Ops",a:"Confirmed.",x:{status:"Confirmed"}}];
const emails14400=[{t:"May 14, 9:21 AM",f:"Noah LiDestri",r:"Cortina",a:"PO issued. Kroger WCCB 504cs.",x:{shipDate:"May 27",dest:"Kroger Forest Park GA",total:"$15,724.80"}},{t:"May 14, 9:38 AM",f:"Maria Restrepo",r:"DC Ops",a:"Confirmed.",x:{status:"Confirmed"}}];
const wkReports=[{wk:"WK15",dt:"May 18, 2026",hl:"Velocity decline 4th straight week. OTIF L4W recovered to 94.85%. SQEP clean. Instock 99.55%.",kpis:[{l:"POS",v:"$42,878",d:"down 10.2%",c:"#DC2626"},{l:"POS Qty",v:"8,798",d:"down 10.4%",c:"#DC2626"},{l:"WCCB U/S/W",v:"2.16",d:"was 2.43",c:"#DC2626"},{l:"PBG U/S/W",v:"1.01",d:"was 1.17",c:"#DC2626"},{l:"Instock",v:"99.55%",d:"",c:"#059669"},{l:"OTIF L4W",v:"94.85%",d:"In Full 100%",c:"#059669"},{l:"Store WOS",v:"5.6",d:"was 7.5",c:"#059669"},{l:"WH WOS",v:"12.3",d:"",c:"#D97706"}],findings:[{n:"01",t:"4th straight weekly decline",d:"WK12: 10,931 to WK15: 8,798. Down 19.5% in 4 weeks.",act:"Regional velocity analysis",own:"Sales / Blayn",due:"Fri 5/23"},{n:"02",t:"SQEP perfect - 100% all categories",d:"Zero defects, $0 charges. Turnaround from WK13 (17 late ASN).",act:"Maintain discipline",own:"Logistics",due:"Ongoing"},{n:"03",t:"OTIF L4W 94.85% On Time, 100% In Full",d:"4,074 cases ordered, 3,864 on time, 210 late, 0 unfilled.",act:"Review 210 late cases",own:"3PL",due:"Fri 5/23"},{n:"04",t:"Markdowns climbing - $1,785 LW, $16,976 YTD",d:"WCCB $1,117 / PBG $668 last week. Margin pressure.",act:"Markdown driver review",own:"Sales / Demand",due:"Mon 5/26"},{n:"05",t:"WH heavy WCCB, PBG supply risk",d:"458 packs WCCB vs 128 PBG. PBG only 756 planned June.",act:"Flag PBG supply risk",own:"Demand Planning",due:"Wed 5/21"}],todos:[{dt:"Wed 5/21",t:"PBG supply review"},{dt:"Fri 5/23",t:"Regional velocity analysis"},{dt:"Mon 5/26",t:"Markdown driver review"}],src:"blayn@bentonvillemerchants.com",subj:"Dirty Cookie | Weekly Reporting | WK15"},{wk:"WK13",dt:"May 5, 2026",hl:"First WoW velocity decline. ASN compliance slipping.",kpis:[{l:"POS",v:"$48.9K",d:"down 8.2%",c:"#DC2626"},{l:"OTIF 4wk",v:"49.4%",d:"Target 95%",c:"#DC2626"},{l:"Late ASN",v:"17",d:"7 on Apr 29",c:"#D97706"}],findings:[{n:"01",t:"Velocity declined both SKUs",d:"WC -8.3%, PB -8.7%.",act:"Velocity decomp",own:"Sales",due:"Fri 5/9"}],todos:[{dt:"Wed 5/7",t:"ASN root-cause"}],src:"blayn@bentonvillemerchants.com",subj:"Dirty Cookie | Weekly Reporting | WK13"}];
const transitions=[{id:"TR-001",from:"WCCB 12ct",to:"WCCB 8ct",launch:"2026-07-14",cutoff:"2026-06-30",status:"planning",notes:"12 CU to 8 per case. New UPC.",checks:[{t:"New UPC assigned",d:false},{t:"NetSuite product number",d:false},{t:"8ct packaging ordered",d:false},{t:"Assemblers adjusted",d:false},{t:"DOT informed",d:false},{t:"Old SKU depletion plan",d:false}]}];
const alerts=[{m:"PO14371 (Kroger) ships in 1 day (May 21). 504cs WCCB.",s:"crit"},{m:"REESE'S PB Chips - 35d lead, expiring Jul 2026.",s:"crit"},{m:"PBG at DOT: no incoming replenishment.",s:"warn"},{m:"PO14201 - awaiting WM payment day 40.",s:"warn"},{m:"Brown Sugar + Eggs have expired lots.",s:"crit"}];
const reorderFG=[{n:"PBG",av:24060,v:3200,so:7.5,ld:14,sg:15000,u:"yellow"},{n:"WCCB",av:50196,v:4800,so:10.5,ld:10,sg:0,u:"green"}];
const reorderRM=[{n:"REESE'S PB Chips",sp:"Hershey's / Barry Callebaut",oh:10386,us:890,so:11.7,ld:35,sg:25000,u:"red"},{n:"Eggs",sp:"Michael Foods",oh:7613,us:380,so:20.0,ld:3,sg:4000,u:"yellow"},{n:"Flour",sp:"Ardent Mills / Gold Medal",oh:95885,us:1630,so:58.8,ld:14,sg:0,u:"green"}];
const allocPOs=[{po:"PO14326",sku:"WCCB",cs:720,ab:50196,al:720,aa:49476,c:"full"},{po:"PO14340",sku:"PBG",cs:6000,ab:24060,al:6000,aa:18060,c:"full"},{po:"PO14352",sku:"PBG",cs:8000,ab:12060,al:8000,aa:4060,c:"low"},{po:"PO14358",sku:"PBG",cs:6000,ab:4060,al:4060,aa:-1940,c:"short"}];
const Pill = ({s}) => {const m={shipped:["#EDE9FE","#6D28D9","Shipped"],delivered:["#DCFCE7","#15803D","Delivered"],pending:["#F3F4F6",GR,"Pending"],paid_national:["#DBEAFE","#1D4ED8","Cortina Paid"],paid_dc:["#DCFCE7","#15803D","Paid"],awaiting_walmart:["#FEF9C3","#A16207","Awaiting WM"],active:["#DCFCE7","#15803D","Active"],upcoming:["#EDE9FE","#6D28D9","Upcoming"],planning:["#FEF9C3","#A16207","Planning"],good:["#DCFCE7","#15803D","Good"],almost_expired:["#FEF9C3","#A16207","Expiring"],partial_expired:["#FEE2E2","#991B1B","Exp Lots"]};const v=m[s]||m.pending;return (<span style={{display:"inline-block",padding:"3px 10px",borderRadius:100,fontSize:10,fontWeight:600,background:v[0],color:v[1],whiteSpace:"nowrap"}}>{v[2]}</span>);};
const th={padding:"8px 10px",textAlign:"left",fontSize:9,fontWeight:700,color:GR,textTransform:"uppercase",letterSpacing:"0.06em",borderBottom:"2px solid "+LT};const thR={...th,textAlign:"right"};const thC={...th,textAlign:"center"};
const batchCalc=(rm)=>{if(!rm.usage||!rm.usage.length) return null;const t=rm.usage.reduce((s,u)=>s+u.q,0);if(!t) return null;const b=Math.floor(rm.qty/t);const w=(rm.qty/(t*1.2)).toFixed(1);return {b,w,tight:parseFloat(w)<rm.lead/7*1.5};};
const DaysTag=({d})=>{const c=d<=1?"#DC2626":d<=3?"#D97706":d<=7?"#A16207":"#059669";const bg=d<=1?"#FEE2E2":d<=3?"#FEF9C3":d<=7?"#FFFBEB":"#F0FDF4";return (<span style={{padding:"2px 7px",borderRadius:100,fontSize:9,fontWeight:700,color:c,background:bg}}>{d<=0?"TODAY":d+"d"}</span>);};
export default function App(){
const[page,setPage]=useState("orders");const[sel,setSel]=useState(null);const[invView,setInvView]=useState("warehouse");const[invSel,setInvSel]=useState(null);const[collapsed,setCollapsed]=useState({});const[wk,setWk]=useState("WK15");const[refView,setRefView]=useState("products");const[reorderDone,setReorderDone]=useState(false);const[uom,setUom]=useState("Cases");const[retFilter,setRetFilter]=useState("All");const[adjusting,setAdjusting]=useState(null);const[addingOrder,setAddingOrder]=useState(false);const[addingDist,setAddingDist]=useState(false);
const nav=(p)=>{setPage(p);setSel(null);setInvSel(null);setReorderDone(false);setAdjusting(null);setAddingOrder(false)};const toggle=(k)=>setCollapsed(p=>({...p,[k]:!p[k]}));
const fmt=(c)=>uom==="CU"?(c*sc.cuPerCase).toLocaleString():uom==="Cookies"?(c*sc.cookiesPerCase).toLocaleString():uom==="Pallets"?(c/sc.casesPerPallet).toFixed(1):c.toLocaleString();
const rpt=wkReports.find(r=>r.wk===wk)||wkReports[0];
const fPOs=retFilter==="All"?POs:POs.filter(p=>p.ret===retFilter);const retailers=[...new Set(POs.map(p=>p.ret))];
const navItems=[{id:"weekly",l:"Weekly Report"},{id:"_d1",l:"---"},{id:"orders",l:"Product Orders"},{id:"payments",l:"Payments"},{id:"_d2",l:"---"},{id:"inventory",l:"Inventory"},{id:"snapshot",l:"EOM Snapshot"},{id:"_d3",l:"---"},{id:"_sp",l:""},{id:"_d4",l:"---"},{id:"reference",l:"Reference"}];
return (<div style={{fontFamily:"'Outfit',sans-serif",background:BG,minHeight:"100vh",color:DK,display:"flex"}}><link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/>
<div style={{width:190,background:DK,minHeight:"100vh",flexShrink:0,display:"flex",flexDirection:"column"}}><div style={{padding:"18px 14px",borderBottom:"1px solid #3D2D4D"}}><div style={{fontSize:17,fontWeight:900,color:PK,fontStyle:"italic"}}>cookie central</div><div style={{fontSize:8,color:GR,marginTop:3,textTransform:"uppercase",letterSpacing:"0.08em"}}>Walmart + Kroger</div></div>
<div style={{padding:"8px 6px",flex:1}}>{navItems.map((n,i)=>{if(n.l==="---") return (<div key={i} style={{height:1,background:"#3D2D4D",margin:"5px 8px"}}/>);if(n.l==="") return (<div key={i} style={{flex:1}}/>);return (<button key={n.id} onClick={()=>nav(n.id)} style={{display:"block",width:"100%",padding:"8px 10px",borderRadius:7,border:"none",background:page===n.id?"rgba(194,24,91,0.15)":"transparent",color:page===n.id?PK:"#B8A8C8",fontSize:12,fontWeight:page===n.id?700:500,cursor:"pointer",fontFamily:"'Outfit'",marginBottom:1,textAlign:"left"}}>{n.l}</button>);})}</div>
<div style={{padding:"8px 12px",borderTop:"1px solid #3D2D4D"}}><div style={{fontSize:7,color:GR,textTransform:"uppercase",marginBottom:4}}>UOM</div><div style={{display:"flex",flexWrap:"wrap",gap:2}}>{["Cases","CU","Cookies","Pallets"].map(u=>(<button key={u} onClick={()=>setUom(u)} style={{padding:"2px 6px",borderRadius:4,border:"none",fontSize:8,fontWeight:uom===u?700:400,background:uom===u?"rgba(194,24,91,0.2)":"transparent",color:uom===u?PK:"#B8A8C8",cursor:"pointer",fontFamily:"'Outfit'"}}>{u}</button>))}</div>
<div style={{fontSize:7,color:"#5B4B6B",marginTop:8}}>Shahira (CEO) | Marc (COO)</div><div style={{fontSize:7,color:"#4D3D5D"}}>David / Paul (Biz Exec)</div><div style={{fontSize:7,color:"#4D3D5D"}}>Maria (Ops) | Caroline (Admin)</div>
<div style={{fontSize:7,color:"#3D2D4D",marginTop:4}}>systems@dirtycookie.com</div><div style={{fontSize:7,color:"#3D2D4D"}}>Demo data only</div></div></div>

<div style={{flex:1,minWidth:0,maxHeight:"100vh",overflowY:"auto"}}><div style={{padding:"18px 22px"}}>

{/* ====== PRODUCT ORDERS ====== */}
{page==="orders"&&!sel&&(<>
<div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>{[{l:"Active POs",v:fPOs.length},{l:"Pending Ship",v:fPOs.filter(p=>p.ship==="pending").length},{l:"In Transit",v:fPOs.filter(p=>p.ship==="shipped").length},{l:"Delivered",v:fPOs.filter(p=>p.ship==="delivered").length},{l:"Unpaid",v:fPOs.filter(p=>p.paidAmt==="$0").length}].map((s,i)=>(<div key={i} style={{background:CD,borderRadius:10,padding:"12px 14px",flex:"1 1 0",minWidth:90,border:"1px solid "+LT}}><div style={{fontSize:18,fontWeight:800}}>{s.v}</div><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase",marginTop:1}}>{s.l}</div></div>))}</div>
<div style={{background:CD,borderRadius:10,padding:"8px 12px",marginBottom:12,border:"1px solid "+LT}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:4}}>Attention ({alerts.length})</div>{alerts.map((a,i)=>(<div key={i} style={{display:"flex",gap:5,padding:"2px 0",fontSize:10,color:MD,borderTop:i?"1px solid "+BG:"none"}}><span style={{width:5,height:5,borderRadius:"50%",background:a.s==="crit"?"#EF4444":"#F59E0B",marginTop:4,flexShrink:0}}/>{a.m}</div>))}</div>
<div style={{display:"flex",gap:3,marginBottom:10}}>{["All",...retailers].map(r=>(<button key={r} onClick={()=>setRetFilter(r)} style={{padding:"4px 12px",borderRadius:6,border:"1px solid "+(retFilter===r?PK:LT),background:retFilter===r?"#FCE7F3":CD,color:retFilter===r?PK:GR,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit'"}}>{r}{r!=="All"&&<span style={{marginLeft:4,fontSize:9,color:retFilter===r?PK:LT}}>({POs.filter(p=>p.ret===r).length})</span>}</button>))}</div>
<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:PC}}>{["PO","Ret","MABD","Days","Products",uom,"Ship","Payment"].map(h=>(<th key={h} style={th}>{h}</th>))}</tr></thead>
<tbody>{fPOs.map(po=>{const d=po.ship==="pending"?daysTo(po.shipDt):null;return (<tr key={po.id} onClick={()=>setSel(po)} style={{cursor:"pointer",borderBottom:"1px solid "+BG}} onMouseEnter={e=>e.currentTarget.style.background=PC} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><td style={{padding:"8px",fontWeight:700}}>{po.id}</td><td style={{padding:"8px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:8,fontWeight:600,background:po.ret==="Kroger"?"#DBEAFE":"#FCE7F3",color:po.ret==="Kroger"?"#1D4ED8":PK}}>{po.ret}</span></td><td style={{padding:"8px",fontWeight:600}}>{po.mabd}</td><td style={{padding:"8px"}}>{d!==null?(<DaysTag d={d}/>):(<span style={{color:GR,fontSize:9}}>{po.ship}</span>)}</td><td style={{padding:"8px",fontSize:10}}>{po.lines.map(l=>(<div key={l.sku}><span style={{fontWeight:600}}>{l.sku}</span> <span style={{color:GR}}>{l.qty}cs</span></div>))}</td><td style={{padding:"8px",fontWeight:600}}>{fmt(po.cs)}</td><td style={{padding:"8px"}}><Pill s={po.ship}/></td><td style={{padding:"8px"}}><Pill s={po.pay}/></td></tr>);})}</tbody></table>
<div style={{padding:"5px 12px",fontSize:8,color:GR,fontStyle:"italic",borderTop:"1px solid "+LT}}>Sorted by urgency. Last synced: May 20, 2026 9:15 AM via NetSuite.</div></div>
</>)}

{/* PO DETAIL */}
{page==="orders"&&sel&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT}}>
<div style={{padding:"16px 18px",borderBottom:"1px solid "+LT,display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:22,fontWeight:900}}>{sel.id} <span style={{fontSize:12,color:GR}}>/ {sel.inv}</span></div><div style={{display:"flex",gap:5,marginTop:5}}><Pill s={sel.ship}/><Pill s={sel.pay}/><span style={{padding:"3px 8px",borderRadius:100,fontSize:9,fontWeight:600,background:sel.ret==="Kroger"?"#DBEAFE":"#FCE7F3",color:sel.ret==="Kroger"?"#1D4ED8":PK}}>{sel.ret}</span>{sel.turn&&<span style={{padding:"3px 8px",borderRadius:100,fontSize:9,fontWeight:600,background:"#FCE7F3",color:PK}}>{sel.turn}</span>}</div></div><button onClick={()=>setSel(null)} style={{background:BG,border:"1px solid "+LT,borderRadius:7,padding:"5px 12px",fontSize:10,fontWeight:600,color:MD,cursor:"pointer",fontFamily:"'Outfit'",height:"fit-content"}}>Back</button></div>
<div style={{padding:"12px 18px",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{[{l:"Invoice",v:sel.inv},{l:"Orig Ship",v:sel.origShip||"--"},{l:"Actual Ship",v:sel.actShip||"--",hl:sel.origShip!==sel.actShip&&sel.actShip},{l:"MABD",v:sel.mabd},{l:"Carrier",v:sel.carrier||"TBD"},{l:"Terms",v:sel.terms},{l:uom,v:fmt(sel.cs)},{l:"BOL",v:sel.bol?"Yes":"Pending"}].map((it,i)=>(<div key={i} style={{background:it.hl?"#FCE7F3":BG,borderRadius:8,padding:"8px 10px",border:it.hl?"1px solid "+PK+"33":"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>{it.l}</div><div style={{fontSize:13,fontWeight:700,color:it.hl?PK:DK,marginTop:2}}>{it.v}</div></div>))}</div>
<div style={{padding:"0 18px 12px"}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}>Line Items</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:PC}}><th style={th}>SKU</th><th style={thR}>Cases</th><th style={thR}>Rev/cs</th><th style={thR}>Line Total</th></tr></thead><tbody>{sel.lines.map(l=>(<tr key={l.sku} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"7px 8px",fontWeight:700}}>{l.sku}</td><td style={{padding:"7px 8px",textAlign:"right"}}>{l.qty.toLocaleString()}</td><td style={{padding:"7px 8px",textAlign:"right",color:GR}}>${sel.revPerCs.toFixed(2)}</td><td style={{padding:"7px 8px",textAlign:"right",fontWeight:600}}>${(l.qty*sel.revPerCs).toLocaleString()}</td></tr>))}</tbody></table></div>
{sel.nova&&<div style={{padding:"0 18px 12px"}}><div style={{background:"#FEF9C3",borderRadius:8,padding:"8px 12px",border:"1px solid #FDE68A",fontSize:10,color:"#92400E"}}><strong>NOVA:</strong> {sel.nova}</div></div>}
{sel.id==="PO14326"&&(<><div style={{padding:"0 18px 12px"}}><div style={{background:"linear-gradient(135deg,#FCE7F3,#EDE9FE)",borderRadius:10,padding:"10px 14px"}}><div style={{fontSize:10,fontWeight:700,color:PK}}>AI Insight</div><div style={{fontSize:10,color:MD,lineHeight:1.5}}>Ship pulled forward 7 days. Freight by Cortina via SunTeck TTS.</div></div></div><div style={{padding:"0 18px 14px"}}><div style={{fontSize:8,fontWeight:700,color:"#6D28D9",textTransform:"uppercase",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}>Email Thread ({emails14326.length})</div><div style={{borderLeft:"2px solid "+LT,marginLeft:3}}>{emails14326.map((em,i)=>(<div key={i} style={{padding:"5px 0 5px 14px",borderBottom:"1px solid "+BG,position:"relative"}}><div style={{position:"absolute",left:-4,top:8,width:6,height:6,borderRadius:"50%",background:CD,border:"2px solid "+PM}}/><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:700,fontSize:10}}>{em.f} <span style={{fontWeight:400,color:GR}}>{em.r}</span></span><span style={{fontSize:8,color:GR}}>{em.t}</span></div><div style={{fontSize:10,fontWeight:600,marginTop:1}}>{em.a}</div>{em.x&&<div style={{marginTop:2,display:"flex",gap:3,flexWrap:"wrap"}}>{Object.entries(em.x).map(([k,v])=>(<span key={k} style={{background:BG,border:"1px solid "+LT,padding:"1px 4px",borderRadius:4,fontSize:8,fontWeight:600}}>{k}: {v}</span>))}</div>}</div>))}</div></div></>)}
{(sel.id==="PO14371"||sel.id==="PO14400")&&(<div style={{padding:"0 18px 14px"}}><div style={{fontSize:8,fontWeight:700,color:"#6D28D9",textTransform:"uppercase",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}>Email Thread</div><div style={{borderLeft:"2px solid "+LT,marginLeft:3}}>{(sel.id==="PO14371"?emails14371:emails14400).map((em,i)=>(<div key={i} style={{padding:"5px 0 5px 14px",borderBottom:"1px solid "+BG,position:"relative"}}><div style={{position:"absolute",left:-4,top:8,width:6,height:6,borderRadius:"50%",background:CD,border:"2px solid "+PM}}/><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:700,fontSize:10}}>{em.f} <span style={{fontWeight:400,color:GR}}>{em.r}</span></span><span style={{fontSize:8,color:GR}}>{em.t}</span></div><div style={{fontSize:10,fontWeight:600,marginTop:1}}>{em.a}</div>{em.x&&<div style={{marginTop:2,display:"flex",gap:3,flexWrap:"wrap"}}>{Object.entries(em.x).map(([k,v])=>(<span key={k} style={{background:BG,border:"1px solid "+LT,padding:"1px 4px",borderRadius:4,fontSize:8,fontWeight:600}}>{k}: {v}</span>))}</div>}</div>))}</div><div style={{marginTop:6,fontSize:9,color:GR,fontStyle:"italic"}}>CC: marc@, smarei@, dlandeck@, orders@</div></div>)}
</div>)}

{/* ====== PAYMENTS ====== */}
{page==="payments"&&!sel&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,overflow:"hidden"}}><div style={{padding:"10px 12px 5px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:8,fontWeight:700,color:GR,textTransform:"uppercase"}}>Click PO for detail | Last synced: May 20 9:15 AM</div><div style={{display:"flex",gap:3}}>{["All",...retailers].map(r=>(<button key={r} onClick={()=>setRetFilter(r)} style={{padding:"2px 8px",borderRadius:4,border:"1px solid "+(retFilter===r?PK:LT),background:retFilter===r?"#FCE7F3":"transparent",color:retFilter===r?PK:GR,fontSize:8,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit'"}}>{r}</button>))}</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:PC}}>{["PO","Ret","Invoice",uom,"Amt","Paid","Terms","Cortina","WM/Ret"].map(h=>(<th key={h} style={th}>{h}</th>))}</tr></thead><tbody>{fPOs.filter(p=>p.ship!=="pending").map(po=>(<tr key={po.id} onClick={()=>setSel(po)} style={{cursor:"pointer",borderBottom:"1px solid "+BG,background:po.pay==="awaiting_walmart"?"#FFFBEB":"transparent"}} onMouseEnter={e=>e.currentTarget.style.background=PC} onMouseLeave={e=>e.currentTarget.style.background=po.pay==="awaiting_walmart"?"#FFFBEB":"transparent"}><td style={{padding:"8px",fontWeight:700}}>{po.id}</td><td style={{padding:"8px"}}><span style={{padding:"1px 5px",borderRadius:3,fontSize:7,fontWeight:600,background:po.ret==="Kroger"?"#DBEAFE":"#FCE7F3",color:po.ret==="Kroger"?"#1D4ED8":PK}}>{po.ret}</span></td><td style={{padding:"8px",color:MD,fontSize:10}}>{po.inv}</td><td style={{padding:"8px",fontWeight:600}}>{fmt(po.cs)}</td><td style={{padding:"8px"}}>{po.payAmt}</td><td style={{padding:"8px",color:po.paidAmt==="$0"?"#DC2626":"#059669",fontWeight:600}}>{po.paidAmt}</td><td style={{padding:"8px",fontSize:9,color:GR}}>{po.terms}</td><td style={{padding:"8px"}}>{["paid_national","paid_dc","awaiting_walmart"].includes(po.pay)?(<Pill s="paid_dc"/>):(<span style={{color:GR}}>--</span>)}</td><td style={{padding:"8px"}}>{po.pay==="paid_dc"?(<Pill s="paid_dc"/>):po.pay==="awaiting_walmart"?(<Pill s="awaiting_walmart"/>):(<span style={{color:GR}}>--</span>)}</td></tr>))}</tbody></table></div>)}
{page==="payments"&&sel&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:18}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div><div style={{fontSize:20,fontWeight:900}}>{sel.id} <span style={{fontSize:11,color:GR}}>/ {sel.inv}</span></div><div style={{display:"flex",gap:5,marginTop:4}}><Pill s={sel.ship}/><Pill s={sel.pay}/><span style={{padding:"3px 8px",borderRadius:100,fontSize:9,fontWeight:600,background:sel.ret==="Kroger"?"#DBEAFE":"#FCE7F3",color:sel.ret==="Kroger"?"#1D4ED8":PK}}>{sel.ret}</span></div></div><button onClick={()=>setSel(null)} style={{background:BG,border:"1px solid "+LT,borderRadius:7,padding:"5px 12px",fontSize:10,fontWeight:600,color:MD,cursor:"pointer",fontFamily:"'Outfit'",height:"fit-content"}}>Back</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginBottom:14}}>{[{l:"Invoice Amt",v:sel.payAmt},{l:"Paid",v:sel.paidAmt,hl:sel.paidAmt==="$0"},{l:"Outstanding",v:sel.paidAmt==="$0"?sel.payAmt:"$0",hl:sel.paidAmt==="$0"},{l:"Terms",v:sel.terms}].map((it,i)=>(<div key={i} style={{background:it.hl?"#FEF2F2":BG,borderRadius:8,padding:"10px 12px",border:"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>{it.l}</div><div style={{fontSize:16,fontWeight:800,color:it.hl?"#DC2626":DK,marginTop:2}}>{it.v}</div></div>))}</div>
<div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}>What was ordered</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:11,marginBottom:12}}><thead><tr style={{background:PC}}><th style={th}>SKU</th><th style={thR}>Cases</th><th style={thR}>Rev/cs</th><th style={thR}>Total</th></tr></thead><tbody>{sel.lines.map(l=>(<tr key={l.sku} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"7px 8px",fontWeight:700}}>{l.sku}</td><td style={{padding:"7px 8px",textAlign:"right"}}>{l.qty.toLocaleString()}</td><td style={{padding:"7px 8px",textAlign:"right",color:GR}}>${sel.revPerCs.toFixed(2)}</td><td style={{padding:"7px 8px",textAlign:"right",fontWeight:600}}>${(l.qty*sel.revPerCs).toLocaleString()}</td></tr>))}</tbody></table>
{sel.nova&&<div style={{marginBottom:12}}><div style={{fontSize:8,fontWeight:700,color:"#A16207",textTransform:"uppercase",marginBottom:3}}>NOVA Changes</div><div style={{background:"#FEF9C3",borderRadius:6,padding:"8px 10px",border:"1px solid #FDE68A",fontSize:10,color:"#92400E"}}>{sel.nova}</div></div>}
<div style={{fontSize:8,fontWeight:700,color:MD,textTransform:"uppercase",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}>Payment timeline ({sel.terms})</div><div style={{display:"flex",gap:8}}>{[{l:"Ship",v:sel.actShip||sel.origShip||sel.dt},{l:sel.ret==="Kroger"?"Cortina to DC":"Cortina to DC (30d)",v:["paid_national","paid_dc"].includes(sel.pay)?"Paid":"Pending",g:["paid_national","paid_dc"].includes(sel.pay)},{l:sel.ret==="Kroger"?"Kroger to Cortina":"WM to Cortina (60d)",v:sel.pay==="paid_dc"?"Paid":sel.pay==="awaiting_walmart"?"Awaiting":"Pending",g:sel.pay==="paid_dc"}].map((t,i)=>(<div key={i} style={{flex:1,background:t.g?"#F0FDF4":BG,borderRadius:6,padding:"8px 10px",border:"1px solid "+LT}}><div style={{fontSize:7,color:GR,textTransform:"uppercase"}}>{t.l}</div><div style={{fontSize:11,fontWeight:700,marginTop:1,color:t.g?"#059669":t.v==="Awaiting"?"#D97706":GR}}>{t.v}</div></div>))}</div></div>)}

{/* ====== INVENTORY ====== */}
{page==="inventory"&&(<>
<div style={{display:"flex",gap:3,marginBottom:12}}>{[{k:"warehouse",l:"By Warehouse"},{k:"product",l:"By Product"},{k:"reorder",l:"Reorder"}].map(v=>(<button key={v.k} onClick={()=>{setInvView(v.k);setReorderDone(false);setInvSel(null);setAdjusting(null)}} style={{padding:"5px 12px",borderRadius:6,border:"1px solid "+(invView===v.k?PK:LT),background:invView===v.k?"#FCE7F3":CD,color:invView===v.k?PK:GR,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit'"}}>{v.l}</button>))}</div>

{invView==="warehouse"&&!invSel&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,overflow:"hidden"}}>
<div onClick={()=>toggle("dot")} style={{background:"linear-gradient(135deg,"+DK+",#3D2D4D)",padding:"9px 14px",cursor:"pointer"}}><div style={{fontSize:11,fontWeight:800,color:WH}}>{collapsed.dot?"+ ":"- "}DOT Foods</div><div style={{fontSize:8,color:"#B8A8C8"}}>Redistributor | Last upload: May 18, 3:20 PM</div></div>
{!collapsed.dot&&<table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:PC}}><th style={th}>Product</th><th style={thR}>On-Hand</th><th style={{...thR,color:"#059669"}}>In</th><th style={{...thR,color:"#6D28D9"}}>ToRet</th><th style={{...thR,color:"#D97706"}}>Alloc</th><th style={{...thR,fontWeight:800}}>Avail</th><th style={thC}>Wks</th></tr></thead><tbody>{dotInv.map(d=>{const av=d.onHand-d.alloc;const w=av/d.vel;return (<tr key={d.sku} style={{borderBottom:"1px solid "+BG,background:w<3?"#FFFBEB":"transparent"}}><td style={{padding:"7px 8px",fontWeight:600}}>{d.name}<div style={{fontSize:8,color:GR}}>{d.sku}</div></td><td style={{padding:"7px 8px",textAlign:"right",fontWeight:700}}>{d.onHand.toLocaleString()}</td><td style={{padding:"7px 8px",textAlign:"right",color:d.incoming?"#059669":LT}}>{d.incoming?"+"+d.incoming.toLocaleString():"--"}</td><td style={{padding:"7px 8px",textAlign:"right",color:"#6D28D9"}}>-{d.transit.toLocaleString()}</td><td style={{padding:"7px 8px",textAlign:"right",color:"#D97706"}}>-{d.alloc.toLocaleString()}</td><td style={{padding:"7px 8px",textAlign:"right",fontWeight:800}}>{av.toLocaleString()}</td><td style={{padding:"7px 8px",textAlign:"center"}}><span style={{padding:"2px 6px",borderRadius:100,fontSize:9,fontWeight:700,background:w<3?"#FEF3C7":"#DCFCE7",color:w<3?"#A16207":"#15803D"}}>{w.toFixed(1)}w</span></td></tr>);})}</tbody></table>}
<div onClick={()=>toggle("asm")} style={{background:"linear-gradient(135deg,"+DK+",#3D2D4D)",padding:"9px 14px",cursor:"pointer"}}><div style={{fontSize:11,fontWeight:800,color:WH}}>{collapsed.asm?"+ ":"- "}Assemblers Chicago</div><div style={{fontSize:8,color:"#B8A8C8"}}>Internal inventory | Last upload: Mar 30, 3:42 PM</div></div>
{!collapsed.asm&&<><div style={{padding:"5px 12px 2px"}}><div style={{fontSize:8,fontWeight:600,color:MD,textTransform:"uppercase"}}>Raw Materials - click for Reference detail</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:PC}}><th style={th}>Code</th><th style={th}>Ingredient</th><th style={thR}>Qty</th><th style={thR}>Lead</th><th style={thR}>Makes</th><th style={thR}>Wks</th><th style={thC}>Flag</th></tr></thead><tbody>{rawMats.map(rm=>{const b=batchCalc(rm);return (<tr key={rm.code} onClick={()=>{nav("reference");setRefView("materials");setTimeout(()=>setSel(rm),0)}} style={{borderBottom:"1px solid "+BG,cursor:"pointer",background:rm.flag==="partial_expired"?"#FFF5F5":rm.flag==="almost_expired"?"#FFFBEB":"transparent"}} onMouseEnter={e=>e.currentTarget.style.background=PC} onMouseLeave={e=>e.currentTarget.style.background=rm.flag==="partial_expired"?"#FFF5F5":rm.flag==="almost_expired"?"#FFFBEB":"transparent"}><td style={{padding:"6px 8px",fontWeight:600,color:GR,fontSize:8,fontFamily:"monospace"}}>{rm.code}</td><td style={{padding:"6px 8px",fontWeight:600}}>{rm.name}{rm.expQty&&<span style={{fontSize:8,color:"#DC2626",marginLeft:3}}>({rm.expQty}exp)</span>}</td><td style={{padding:"6px 8px",textAlign:"right",fontWeight:700}}>{rm.qty.toLocaleString()}<span style={{fontSize:8,color:GR,marginLeft:2}}>{rm.unit}</span></td><td style={{padding:"6px 8px",textAlign:"right",color:rm.lead>=21?"#D97706":GR}}>{rm.lead}d</td><td style={{padding:"6px 8px",textAlign:"right",color:b?MD:GR}}>{b?b.b+" batch":"--"}</td><td style={{padding:"6px 8px",textAlign:"right"}}>{b?(<span style={{fontWeight:700,color:b.tight?"#DC2626":"#059669"}}>{b.w}w{b.tight?" !":""}</span>):(<span style={{color:GR}}>--</span>)}</td><td style={{padding:"6px 8px",textAlign:"center"}}><Pill s={rm.flag}/></td></tr>);})}</tbody></table>
<div style={{padding:"5px 12px 2px",borderTop:"1px solid "+LT}}><div style={{fontSize:8,fontWeight:600,color:MD,textTransform:"uppercase"}}>Packaging</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><tbody>{packaging.map(pk=>(<tr key={pk.code} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"5px 8px",fontWeight:600,color:GR,fontSize:8,fontFamily:"monospace",width:60}}>{pk.code}</td><td style={{padding:"5px 8px",fontWeight:600}}>{pk.name}</td><td style={{padding:"5px 8px",textAlign:"right",fontWeight:700}}>{pk.qty.toLocaleString()}<span style={{fontSize:8,color:GR,marginLeft:2}}>{pk.unit}</span></td></tr>))}</tbody></table></>}
</div>)}

{/* BY PRODUCT with detail view */}
{invView==="product"&&!invSel&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,overflow:"hidden"}}>{[{type:"Finished Goods",items:dotInv.map(d=>({n:d.name,k:d.sku,t:d.onHand,locs:[{l:"DOT Foods",q:d.onHand}],vel:d.vel,alloc:d.alloc}))},{type:"Raw Materials",items:rawMats.map(r=>({n:r.name,k:r.code,t:r.qty,u:r.unit,locs:[{l:"Assemblers",q:r.qty}]}))},{type:"Packaging",items:packaging.map(p=>({n:p.name,k:p.code,t:p.qty,u:p.unit,locs:[{l:"Assemblers",q:p.qty}]}))}].map((grp,gi)=>(<div key={gi}><div style={{background:DK,padding:"7px 12px"}}><div style={{fontSize:10,fontWeight:800,color:WH}}>{grp.type.toUpperCase()}</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><tbody>{grp.items.map(it=>(<tr key={it.k} onClick={()=>setInvSel(it)} style={{borderBottom:"1px solid "+BG,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.background=PC} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><td style={{padding:"7px 8px",fontWeight:600}}>{it.n}<div style={{fontSize:8,color:GR}}>{it.k}</div></td><td style={{padding:"7px 8px",textAlign:"right",fontWeight:800,fontSize:12}}>{it.t.toLocaleString()}{it.u&&<span style={{fontSize:8,color:GR,marginLeft:2}}>{it.u}</span>}</td><td style={{padding:"7px 8px",textAlign:"right",color:PK,fontSize:10}}>detail &gt;</td></tr>))}</tbody></table></div>))}<div style={{padding:"5px 12px",fontSize:8,color:GR,fontStyle:"italic",borderTop:"1px solid "+LT}}>Click any item for location breakdown. Last upload: Mar 30.</div></div>)}

{/* BY PRODUCT DETAIL */}
{invView==="product"&&invSel&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:16}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:14}}><div><div style={{fontSize:18,fontWeight:900}}>{invSel.n}</div><div style={{fontSize:9,color:GR,fontFamily:"monospace"}}>{invSel.k}</div></div><button onClick={()=>setInvSel(null)} style={{background:BG,border:"1px solid "+LT,borderRadius:6,padding:"5px 12px",fontSize:10,fontWeight:600,color:MD,cursor:"pointer",fontFamily:"'Outfit'",height:"fit-content"}}>Back</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginBottom:14}}>
<div style={{background:BG,borderRadius:8,padding:"10px 12px",border:"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>Total</div><div style={{fontSize:18,fontWeight:800,marginTop:2}}>{invSel.t.toLocaleString()}{invSel.u&&<span style={{fontSize:10,color:GR,marginLeft:3}}>{invSel.u}</span>}</div></div>
{invSel.vel&&<div style={{background:BG,borderRadius:8,padding:"10px 12px",border:"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>Weekly Velocity</div><div style={{fontSize:18,fontWeight:800,marginTop:2}}>{invSel.vel.toLocaleString()}</div></div>}
{invSel.alloc&&<div style={{background:"#FFFBEB",borderRadius:8,padding:"10px 12px",border:"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>Allocated to POs</div><div style={{fontSize:18,fontWeight:800,marginTop:2,color:"#D97706"}}>{invSel.alloc.toLocaleString()}</div></div>}
{!invSel.vel&&<div style={{background:BG,borderRadius:8,padding:"10px 12px",border:"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>Lots</div><div style={{fontSize:18,fontWeight:800,marginTop:2}}>{invSel.locs.length}</div></div>}
{!invSel.alloc&&<div style={{background:BG,borderRadius:8,padding:"10px 12px",border:"1px solid "+LT}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>Locations</div><div style={{fontSize:18,fontWeight:800,marginTop:2}}>{invSel.locs.length}</div></div>}
</div>
<div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}>Location Breakdown</div>
<table style={{width:"100%",borderCollapse:"collapse",fontSize:12,marginBottom:12}}><thead><tr style={{background:PC}}><th style={th}>Location</th><th style={thR}>Quantity</th><th style={thR}>% of Total</th></tr></thead><tbody>{invSel.locs.filter(l=>l.q>0).map((l,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"8px 10px",fontWeight:600}}>{l.l}</td><td style={{padding:"8px 10px",textAlign:"right",fontWeight:700}}>{l.q.toLocaleString()}{invSel.u&&<span style={{fontSize:9,color:GR,marginLeft:2}}>{invSel.u}</span>}</td><td style={{padding:"8px 10px",textAlign:"right",color:GR}}>{((l.q/invSel.t)*100).toFixed(1)}%</td></tr>))}</tbody></table>
{/* Adjust inventory */}
{!adjusting&&<button onClick={()=>setAdjusting(true)} style={{background:BG,border:"1px solid "+LT,borderRadius:6,padding:"6px 14px",fontSize:10,fontWeight:600,color:PK,cursor:"pointer",fontFamily:"'Outfit'"}}>Adjust Inventory (shrink / expired / damaged)</button>}
{adjusting&&(<div style={{background:BG,borderRadius:8,padding:"12px",border:"1px solid "+LT,marginTop:8}}>
<div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:6}}>Inventory Adjustment</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:8}}>
<div><div style={{fontSize:8,color:GR,marginBottom:2}}>Reason</div><select style={{width:"100%",padding:"6px 8px",borderRadius:5,border:"1px solid "+LT,fontSize:10,fontFamily:"'Outfit'"}}><option>Shrink</option><option>Expired</option><option>Damaged</option><option>Disposed</option><option>Other</option></select></div>
<div><div style={{fontSize:8,color:GR,marginBottom:2}}>Qty to remove</div><input placeholder="0" style={{width:"100%",padding:"6px 8px",borderRadius:5,border:"1px solid "+LT,fontSize:10,fontFamily:"'Outfit'",textAlign:"right",boxSizing:"border-box"}}/></div>
<div><div style={{fontSize:8,color:GR,marginBottom:2}}>Notes</div><input placeholder="Optional" style={{width:"100%",padding:"6px 8px",borderRadius:5,border:"1px solid "+LT,fontSize:10,fontFamily:"'Outfit'",boxSizing:"border-box"}}/></div>
</div>
<div style={{display:"flex",gap:6}}><button onClick={()=>setAdjusting(null)} style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"5px 14px",borderRadius:5,fontWeight:700,fontSize:10,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Confirm Adjustment</button><button onClick={()=>setAdjusting(null)} style={{background:CD,border:"1px solid "+LT,borderRadius:5,padding:"5px 12px",fontSize:10,fontWeight:600,color:GR,cursor:"pointer",fontFamily:"'Outfit'"}}>Cancel</button></div>
<div style={{marginTop:6,fontSize:8,color:GR,fontStyle:"italic"}}>Logged to audit trail. Feeds into EOM Snapshot.</div>
</div>)}
</div>)}

{/* REORDER */}
{invView==="reorder"&&!reorderDone&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT}}><div style={{background:"linear-gradient(135deg,#FCE7F3,#EDE9FE)",padding:"8px 12px",borderRadius:"10px 10px 0 0"}}><div style={{fontSize:10,fontWeight:700,color:PK}}>Preview mode</div><div style={{fontSize:9,color:MD}}>Calculated from inventory + POs + velocity. Reorders via email during honeymoon.</div></div>
<div style={{padding:"8px 12px 3px"}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase"}}>Finished Goods</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr style={{background:PC}}><th style={thC}>!</th><th style={th}>SKU</th><th style={thR}>Avail</th><th style={thR}>Vel</th><th style={thR}>Out</th><th style={thR}>Lead</th><th style={thR}>Sugg</th><th style={{...thR,color:PK}}>Marc</th></tr></thead><tbody>{reorderFG.map((it,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG,background:it.u==="yellow"?"#FFFBEB":"transparent"}}><td style={{padding:"6px",textAlign:"center"}}><span style={{display:"inline-block",width:7,height:7,borderRadius:"50%",background:it.u==="yellow"?"#F59E0B":"#22C55E"}}/></td><td style={{padding:"6px",fontWeight:600}}>{it.n}</td><td style={{padding:"6px",textAlign:"right",fontWeight:700}}>{it.av.toLocaleString()}</td><td style={{padding:"6px",textAlign:"right",color:GR}}>{it.v.toLocaleString()}/w</td><td style={{padding:"6px",textAlign:"right",fontWeight:700,color:it.u==="yellow"?"#D97706":DK}}>{it.so.toFixed(1)}d</td><td style={{padding:"6px",textAlign:"right",color:GR}}>{it.ld}d</td><td style={{padding:"6px",textAlign:"right"}}>{it.sg>0?it.sg.toLocaleString():"--"}</td><td style={{padding:"6px",textAlign:"right"}}><input defaultValue={it.sg>0?it.sg:""} placeholder="--" style={{width:65,padding:"3px 5px",borderRadius:4,border:"1px solid "+LT,fontSize:10,fontFamily:"'Outfit'",textAlign:"right"}}/></td></tr>))}</tbody></table>
<div style={{borderTop:"2px solid "+LT,margin:"4px 0"}}/>
<div style={{padding:"6px 12px 3px"}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase"}}>Raw Materials</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr style={{background:PC}}><th style={thC}>!</th><th style={th}>Item</th><th style={th}>Distributor</th><th style={th}>Brand</th><th style={thR}>OH</th><th style={thR}>Out</th><th style={thR}>Sugg</th><th style={{...thR,color:PK}}>Marc</th></tr></thead><tbody>{reorderRM.map((it,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG,background:it.u==="red"?"#FEF2F2":it.u==="yellow"?"#FFFBEB":"transparent"}}><td style={{padding:"6px",textAlign:"center"}}><span style={{display:"inline-block",width:7,height:7,borderRadius:"50%",background:it.u==="red"?"#EF4444":it.u==="yellow"?"#F59E0B":"#22C55E"}}/></td><td style={{padding:"6px",fontWeight:600}}>{it.n}{it.u==="red"&&it.so<it.ld&&<div style={{fontSize:7,color:"#DC2626"}}>Past reorder</div>}</td><td style={{padding:"6px"}}><select style={{padding:"3px 4px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",width:"100%"}}><option>St Charles</option><option>Dawn</option></select></td><td style={{padding:"6px"}}><select style={{padding:"3px 4px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",width:"100%"}}>{it.sp.split(" / ").map(b=>(<option key={b}>{b}</option>))}</select></td><td style={{padding:"6px",textAlign:"right"}}>{it.oh.toLocaleString()}</td><td style={{padding:"6px",textAlign:"right",fontWeight:700,color:it.u==="red"?"#DC2626":it.u==="yellow"?"#D97706":DK}}>{it.so.toFixed(0)}d</td><td style={{padding:"6px",textAlign:"right"}}>{it.sg>0?it.sg.toLocaleString():"--"}</td><td style={{padding:"6px",textAlign:"right"}}><input defaultValue={it.sg>0?it.sg:""} placeholder="--" style={{width:65,padding:"3px 5px",borderRadius:4,border:"1px solid "+LT,fontSize:10,fontFamily:"'Outfit'",textAlign:"right"}}/></td></tr>))}</tbody></table>
<div style={{padding:"8px 12px",borderTop:"1px solid "+LT,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:8,color:GR}}>70% 8-wk vel + 30% open POs | Select distributor + brand per ingredient before confirming</div><button onClick={()=>setReorderDone(true)} style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"6px 16px",borderRadius:7,fontWeight:700,fontSize:10,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Confirm</button></div></div>)}
{invView==="reorder"&&reorderDone&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div style={{fontSize:15,fontWeight:900}}>Order confirmed</div><div style={{display:"flex",gap:5}}><button onClick={()=>setReorderDone(false)} style={{background:BG,border:"1px solid "+LT,borderRadius:6,padding:"4px 10px",fontSize:9,fontWeight:600,color:MD,cursor:"pointer",fontFamily:"'Outfit'"}}>Edit</button><button style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"4px 12px",borderRadius:6,fontWeight:700,fontSize:9,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Export PDF</button></div></div>
<div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:5}}>Allocation</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr style={{background:PC}}><th style={th}>PO</th><th style={th}>SKU</th><th style={thR}>Ord</th><th style={thR}>Avail</th><th style={thR}>Alloc</th><th style={thR}>After</th><th style={thC}>Cov</th></tr></thead><tbody>{allocPOs.map((a,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG,background:a.c==="short"?"#FEF2F2":a.c==="low"?"#FFFBEB":"transparent"}}><td style={{padding:"6px",fontWeight:700}}>{a.po}</td><td style={{padding:"6px"}}>{a.sku}</td><td style={{padding:"6px",textAlign:"right"}}>{a.cs.toLocaleString()}</td><td style={{padding:"6px",textAlign:"right",color:GR}}>{a.ab.toLocaleString()}</td><td style={{padding:"6px",textAlign:"right",fontWeight:700,color:"#059669"}}>{a.al.toLocaleString()}</td><td style={{padding:"6px",textAlign:"right",fontWeight:700,color:a.aa<0?"#DC2626":a.c==="low"?"#D97706":DK}}>{a.aa.toLocaleString()}</td><td style={{padding:"6px",textAlign:"center"}}><span style={{padding:"2px 5px",borderRadius:100,fontSize:8,fontWeight:700,background:a.c==="full"?"#DCFCE7":a.c==="low"?"#FEF3C7":"#FEE2E2",color:a.c==="full"?"#15803D":a.c==="low"?"#A16207":"#991B1B"}}>{a.c==="full"?"OK":a.c==="low"?"Low":"Short"}</span></td></tr>))}</tbody></table></div>)}
</>)}

{/* ====== WEEKLY REPORT ====== */}
{page==="weekly"&&(<><div style={{display:"flex",gap:5,marginBottom:12}}>{wkReports.map(r=>(<button key={r.wk} onClick={()=>setWk(r.wk)} style={{padding:"6px 12px",borderRadius:7,border:wk===r.wk?"2px solid "+PK:"1px solid "+LT,background:wk===r.wk?"#FCE7F3":CD,color:wk===r.wk?PK:DK,fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"'Outfit'"}}>{r.wk}<div style={{fontSize:8,color:wk===r.wk?PK:GR}}>{r.dt}</div></button>))}<button style={{marginLeft:"auto",background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"6px 12px",borderRadius:7,fontWeight:700,fontSize:9,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Check for new</button></div>
<div style={{background:CD,borderRadius:10,border:"1px solid "+LT}}><div style={{padding:"14px 18px 8px"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:3}}><div style={{fontSize:20,fontWeight:900}}>{rpt.wk}</div><span style={{padding:"2px 7px",borderRadius:100,fontSize:8,fontWeight:600,background:"#EDE9FE",color:"#6D28D9"}}>Auto from email</span><span style={{fontSize:8,color:GR}}>Walmart only. Kroger reporting source TBD.</span></div><div style={{fontSize:8,color:GR}}>From: {rpt.src} | {rpt.subj} | Mon 9:30 AM CT</div><div style={{marginTop:6,padding:"7px 10px",background:BG,borderRadius:7,fontSize:11,fontWeight:600}}>{rpt.hl}</div></div>
<div style={{padding:"0 18px 12px",display:"flex",gap:7,flexWrap:"wrap"}}>{rpt.kpis.map((k,i)=>(<div key={i} style={{background:CD,borderRadius:8,padding:"8px 12px",border:"1px solid "+LT,flex:"1 1 0",minWidth:80}}><div style={{fontSize:8,color:GR,fontWeight:600,textTransform:"uppercase"}}>{k.l}</div><div style={{fontSize:16,fontWeight:800,marginTop:2}}>{k.v}</div>{k.d&&<div style={{fontSize:9,fontWeight:600,color:k.c,marginTop:1}}>{k.d}</div>}</div>))}</div>
{rpt.findings.length>0&&<div style={{padding:"0 18px 12px"}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:5}}>Findings</div>{rpt.findings.map((f,i)=>(<div key={i} style={{marginBottom:5,background:BG,borderRadius:8,padding:"8px 12px",border:"1px solid "+LT}}><div style={{display:"flex",gap:5,marginBottom:2}}><span style={{fontWeight:800,color:PK,fontFamily:"monospace",fontSize:10}}>{f.n}</span><span style={{fontWeight:700,fontSize:11}}>{f.t}</span></div><div style={{fontSize:10,color:MD,marginBottom:4}}>{f.d}</div><div style={{display:"flex",gap:5,fontSize:8,flexWrap:"wrap"}}><span style={{background:CD,padding:"2px 5px",borderRadius:4,border:"1px solid "+LT}}>Action: {f.act}</span><span style={{background:CD,padding:"2px 5px",borderRadius:4,border:"1px solid "+LT}}>Owner: {f.own}</span><span style={{background:CD,padding:"2px 5px",borderRadius:4,border:"1px solid "+LT,color:PK,fontWeight:700}}>Due: {f.due}</span></div></div>))}</div>}
{rpt.todos.length>0&&<div style={{padding:"0 18px 12px"}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:4}}>EOS To-Dos</div><div style={{background:DK,borderRadius:8,padding:"8px 12px"}}>{rpt.todos.map((td,i)=>(<div key={i} style={{display:"flex",gap:8,padding:"3px 0",borderBottom:i<rpt.todos.length-1?"1px solid #3D2D4D":"none"}}><span style={{fontSize:9,fontWeight:700,color:PK,minWidth:50}}>{td.dt}</span><span style={{fontSize:9,color:"#E8E0F0"}}>{td.t}</span></div>))}</div></div>}
<div style={{padding:"0 18px 10px"}}><div style={{fontSize:8,fontWeight:700,color:"#6D28D9",textTransform:"uppercase",marginBottom:3}}>EOS Rocks (placeholder)</div><div style={{background:"#FAF5FF",borderRadius:6,padding:"6px 10px",border:"1px solid #EDE9FE",color:"#6D28D9",fontSize:9}}>Set during quarterly planning.</div></div>
<div style={{padding:"0 18px 10px"}}><div style={{fontSize:8,fontWeight:700,color:"#6D28D9",textTransform:"uppercase",marginBottom:3}}>EOS Issues List</div><div style={{background:"#FAF5FF",borderRadius:6,padding:"6px 10px",border:"1px solid #EDE9FE",fontSize:9}}>{alerts.map((a,i)=>(<div key={i} style={{display:"flex",gap:4,padding:"1px 0",color:MD}}><span style={{width:4,height:4,borderRadius:"50%",background:a.s==="crit"?"#EF4444":"#F59E0B",marginTop:4,flexShrink:0}}/>{a.m}</div>))}<div style={{marginTop:3,fontSize:8,color:GR,fontStyle:"italic"}}>IDS in L10. Top 3. Solved = To-Do.</div></div></div>
<div style={{padding:"0 18px 10px"}}><div style={{background:"#F0F9FF",borderRadius:6,padding:"7px 10px",border:"1px dashed #93C5FD",fontSize:9,color:"#1E40AF",display:"flex",gap:6,alignItems:"flex-start"}}><span style={{fontWeight:700,flexShrink:0}}>Phase 3</span><div>Slack integration: owners receive notifications on assignments and changes, tied to login credentials.</div></div></div></div></>)}

{/* ====== EOM SNAPSHOT ====== */}
{page==="snapshot"&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:16}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:2}}>End of Month - April 2026</div><div style={{fontSize:8,color:GR,marginBottom:12}}>Demo data | Last generated: May 1, 2026</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginBottom:14}}>{[{l:"POs",v:"12",d:"+3 vs Mar"},{l:"Cases Shipped",v:"14,400",d:"+2,100"},{l:"Revenue",v:"$86,400",d:"+$12,600"},{l:"Chargebacks",v:"$0",d:"--"}].map((s,i)=>(<div key={i} style={{background:BG,borderRadius:8,padding:"10px",border:"1px solid "+LT}}><div style={{fontSize:16,fontWeight:800}}>{s.v}</div><div style={{fontSize:7,color:GR,fontWeight:600,textTransform:"uppercase",marginTop:1}}>{s.l}</div><div style={{fontSize:8,color:s.d.includes("+")?"#059669":GR,fontWeight:600,marginTop:2}}>{s.d}</div></div>))}</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginBottom:14}}>{[{l:"Markdowns",v:"$16,976",d:"YTD"},{l:"Shrink",v:"$320",d:"50 lbs brown sugar"},{l:"Fill Rate",v:"100%",d:"0 unfilled"}].map((s,i)=>(<div key={i} style={{background:BG,borderRadius:8,padding:"10px",border:"1px solid "+LT}}><div style={{fontSize:14,fontWeight:800}}>{s.v}</div><div style={{fontSize:7,color:GR,fontWeight:600,textTransform:"uppercase",marginTop:1}}>{s.l}</div><div style={{fontSize:8,color:GR,marginTop:2}}>{s.d}</div></div>))}</div>
{[{t:"Finished Goods",r:[["WCCB","62,196"],["PBG","30,060"]]},{t:"Raw Materials (top 4)",r:rawMats.slice(0,4).map(r=>[r.name,r.qty.toLocaleString()])},{t:"Packaging",r:packaging.map(p=>[p.name,p.qty.toLocaleString()])}].map((sec,si)=>(<div key={si} style={{marginBottom:8}}><div style={{fontSize:8,fontWeight:700,color:MD,textTransform:"uppercase",marginBottom:2}}>{sec.t}</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><tbody>{sec.r.map((r,ri)=>(<tr key={ri} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"4px 8px",fontWeight:600}}>{r[0]}</td><td style={{padding:"4px 8px",textAlign:"right",fontWeight:700}}>{r[1]}</td></tr>))}</tbody></table></div>))}</div>)}

{/* ====== REFERENCE ====== */}
{page==="reference"&&!sel&&(<><div style={{display:"flex",gap:3,marginBottom:12}}>{[{k:"products",l:"Products & UOM"},{k:"materials",l:"Raw Materials"},{k:"transitions",l:"Transitions"}].map(v=>(<button key={v.k} onClick={()=>setRefView(v.k)} style={{padding:"5px 12px",borderRadius:6,border:"1px solid "+(refView===v.k?PK:LT),background:refView===v.k?"#FCE7F3":CD,color:refView===v.k?PK:GR,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"'Outfit'"}}>{v.l}</button>))}</div>
{refView==="products"&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT}}><div style={{margin:"12px",background:BG,borderRadius:8,padding:"10px 14px",border:"1px solid "+LT}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:6}}>WMT Dough conversion</div><div style={{display:"flex",alignItems:"center"}}>{[{l:"Cookie",v:"1"},{l:"CU",v:"4"},{l:"Case",v:"48"},{l:"Pallet",v:"9,072"}].map((u,i,a)=>(<div key={i} style={{display:"flex",alignItems:"center"}}><div style={{textAlign:"center",minWidth:70,padding:"3px 6px"}}><div style={{fontSize:14,fontWeight:800}}>{u.v}</div><div style={{fontSize:9,fontWeight:700,color:PK}}>{u.l}</div></div>{i<a.length-1&&<div style={{fontSize:12,color:LT}}>-</div>}</div>))}</div><div style={{fontSize:8,color:GR,marginTop:3}}>Ti{sc.ti} x Hi{sc.hi} = {sc.casesPerPallet} cs/pallet</div></div>
<table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr style={{background:PC}}><th style={th}>SKU</th><th style={th}>Product</th><th style={th}>Retailer</th><th style={thR}>COG</th><th style={thR}>Rev</th><th style={thC}>Status</th></tr></thead><tbody>{products.map((p,i)=>(<tr key={i} onClick={()=>setSel(p)} style={{borderBottom:"1px solid "+BG,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.background=PC} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><td style={{padding:"7px 8px",fontWeight:600,color:GR,fontSize:8,fontFamily:"monospace"}}>{p.sku}</td><td style={{padding:"7px 8px"}}><div style={{fontWeight:600}}>{p.short}</div><div style={{fontSize:8,color:GR}}>{p.name}</div></td><td style={{padding:"7px 8px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:8,fontWeight:600,background:p.retailer==="Kroger"?"#DBEAFE":"#FCE7F3",color:p.retailer==="Kroger"?"#1D4ED8":PK}}>{p.retailer}</span></td><td style={{padding:"7px 8px",textAlign:"right"}}>{p.cog?"$"+p.cog.toFixed(2):(<span style={{color:LT}}>TBD</span>)}</td><td style={{padding:"7px 8px",textAlign:"right"}}>{p.rev?"$"+p.rev.toFixed(2):(<span style={{color:LT}}>TBD</span>)}</td><td style={{padding:"7px 8px",textAlign:"center"}}><Pill s={p.status}/></td></tr>))}</tbody></table></div>)}
{refView==="materials"&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,overflow:"hidden"}}><div style={{padding:"10px 12px 5px"}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase"}}>Raw materials master - click for distributor detail</div></div><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr style={{background:PC}}><th style={th}>Code</th><th style={th}>Ingredient</th><th style={thR}>Qty</th><th style={thR}>Lead</th><th style={th}>Distributors</th><th style={thC}>Flag</th></tr></thead><tbody>{rawMats.map(rm=>(<tr key={rm.code} onClick={()=>setSel(rm)} style={{borderBottom:"1px solid "+BG,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.background=PC} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><td style={{padding:"6px 8px",fontWeight:600,color:GR,fontSize:8,fontFamily:"monospace"}}>{rm.code}</td><td style={{padding:"6px 8px",fontWeight:600}}>{rm.name}</td><td style={{padding:"6px 8px",textAlign:"right",fontWeight:700}}>{rm.qty.toLocaleString()}</td><td style={{padding:"6px 8px",textAlign:"right",color:rm.lead>=21?"#D97706":GR}}>{rm.lead}d</td><td style={{padding:"6px 8px",fontSize:9,color:MD}}>{rm.distributors.map(d=>d.dist).join(", ")}</td><td style={{padding:"6px 8px",textAlign:"center"}}><Pill s={rm.flag}/></td></tr>))}</tbody></table></div>)}
{refView==="transitions"&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase"}}>Product transitions</div><button style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"4px 10px",borderRadius:5,fontWeight:700,fontSize:9,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>+ New</button></div>{transitions.map((tr,i)=>(<div key={i} style={{background:BG,borderRadius:8,padding:"12px",border:"1px solid "+LT}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:5}}><div><div style={{display:"flex",gap:4,marginBottom:2}}><span style={{fontSize:9,fontWeight:700,color:GR,fontFamily:"monospace"}}>{tr.id}</span><Pill s={tr.status}/></div><div style={{fontSize:13,fontWeight:800}}><span style={{color:GR,textDecoration:"line-through"}}>{tr.from}</span> <span style={{color:LT}}>to</span> {tr.to}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:7,color:GR,textTransform:"uppercase"}}>Launch</div><div style={{fontSize:12,fontWeight:700,color:PK}}>{tr.launch}</div></div></div><div style={{display:"flex",gap:6,marginBottom:8}}><div style={{flex:1,background:CD,borderRadius:5,padding:"7px 9px",border:"1px solid "+LT}}><div style={{fontSize:7,color:GR,textTransform:"uppercase"}}>Cutoff</div><div style={{fontSize:10,fontWeight:700,marginTop:1}}>{tr.cutoff}</div></div><div style={{flex:1,background:CD,borderRadius:5,padding:"7px 9px",border:"1px solid "+PK+"33"}}><div style={{fontSize:7,color:PK,textTransform:"uppercase"}}>Launch</div><div style={{fontSize:10,fontWeight:700,marginTop:1}}>{tr.launch}</div></div></div><div style={{fontSize:9,color:MD,marginBottom:6}}>{tr.notes}</div><div style={{fontSize:7,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:3}}>Checklist</div>{tr.checks.map((c,ci)=>(<div key={ci} style={{display:"flex",gap:5,padding:"2px 0",fontSize:9,color:c.d?GR:DK}}><span>{c.d?"[x]":"[ ]"}</span>{c.t}</div>))}</div>))}</div>)}
</>)}

{/* REF DETAIL - Product */}
{page==="reference"&&sel&&sel.short&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div><div style={{fontSize:18,fontWeight:900}}>{sel.short}</div><div style={{fontSize:10,color:MD}}>{sel.name}</div><div style={{fontSize:8,color:GR,fontFamily:"monospace",marginTop:2}}>{sel.sku}</div><div style={{display:"flex",gap:4,marginTop:3}}><Pill s={sel.status}/><span style={{padding:"3px 8px",borderRadius:100,fontSize:9,fontWeight:600,background:sel.retailer==="Kroger"?"#DBEAFE":"#FCE7F3",color:sel.retailer==="Kroger"?"#1D4ED8":PK}}>{sel.retailer}</span></div></div><button onClick={()=>setSel(null)} style={{background:BG,border:"1px solid "+LT,borderRadius:6,padding:"5px 12px",fontSize:10,fontWeight:600,color:MD,cursor:"pointer",fontFamily:"'Outfit'",height:"fit-content"}}>Back</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginBottom:12}}>{[{l:"COG/cs",v:sel.cog?"$"+sel.cog.toFixed(2):"TBD",e:1},{l:"Rev/cs",v:sel.rev?"$"+sel.rev.toFixed(2):"TBD",e:1},{l:"Margin",v:sel.cog&&sel.rev?((sel.rev-sel.cog)/sel.rev*100).toFixed(1)+"%":"TBD"},{l:"Shelf",v:sel.shelf+"d"},{l:"Launch",v:sel.launch},{l:"Cs/Pallet",v:sc.casesPerPallet+""},{l:"Retailer",v:sel.retailer},{l:"Cook/Cs",v:sc.cookiesPerCase+""}].map((it,i)=>(<div key={i} style={{background:BG,borderRadius:8,padding:"7px 10px",border:"1px solid "+LT}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:7,color:GR,fontWeight:600,textTransform:"uppercase"}}>{it.l}</span>{it.e&&<span style={{fontSize:7,color:PK,cursor:"pointer"}}>edit</span>}</div><div style={{fontSize:12,fontWeight:700,marginTop:2}}>{it.v}</div></div>))}</div>
{sel.note&&<div style={{padding:"6px 10px",background:BG,borderRadius:6,fontSize:9,color:MD,marginBottom:10}}>{sel.note}</div>}
{sel.transNote&&<div style={{padding:"7px 10px",background:"linear-gradient(135deg,#FCE7F3,#EDE9FE)",borderRadius:7,fontSize:9,color:MD,marginBottom:10}}>Transition: {sel.transNote}</div>}
<div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:3}}>Bill of Materials</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr style={{background:PC}}><th style={th}>Ingredient</th><th style={thR}>Per batch</th><th style={thR}>On hand</th><th style={thR}>Lead</th></tr></thead><tbody>{rawMats.filter(rm=>rm.usage.some(u=>u.p===sel.short||u.p==="WCCB"&&sel.short.startsWith("WCCB"))).map(rm=>{const u=rm.usage.find(u=>u.p===sel.short)||rm.usage.find(u=>u.p==="WCCB");return u?(<tr key={rm.code} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"6px 8px",fontWeight:600}}>{rm.name}</td><td style={{padding:"6px 8px",textAlign:"right"}}>{u.q.toLocaleString()} lbs</td><td style={{padding:"6px 8px",textAlign:"right",fontWeight:600}}>{rm.qty.toLocaleString()}</td><td style={{padding:"6px 8px",textAlign:"right",color:rm.lead>=21?"#D97706":GR}}>{rm.lead}d</td></tr>):null;})}</tbody></table></div>)}

{/* REF DETAIL - Raw Material with distributors */}
{page==="reference"&&sel&&sel.code&&(<div style={{background:CD,borderRadius:10,border:"1px solid "+LT,padding:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div><div style={{fontSize:18,fontWeight:900}}>{sel.name}</div><div style={{fontSize:8,color:GR,fontFamily:"monospace"}}>Code: {sel.code}</div></div><button onClick={()=>setSel(null)} style={{background:BG,border:"1px solid "+LT,borderRadius:6,padding:"5px 12px",fontSize:10,fontWeight:600,color:MD,cursor:"pointer",fontFamily:"'Outfit'",height:"fit-content"}}>Back</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginBottom:8}}>{[{l:"On Hand",v:sel.qty.toLocaleString()+" "+sel.unit},{l:"Default Lead",v:sel.lead+"d",hl:sel.lead>=21,e:1,note:"Per-distributor lead times below"},{l:"Lots",v:sel.lots+""},{l:"Expiry",v:sel.exp}].map((it,i)=>(<div key={i} style={{background:it.hl?"#FEF9C3":BG,borderRadius:8,padding:"7px 10px",border:"1px solid "+LT}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:7,color:GR,fontWeight:600,textTransform:"uppercase"}}>{it.l}</span>{it.e&&<span style={{fontSize:7,color:PK,cursor:"pointer"}}>edit</span>}</div><div style={{fontSize:12,fontWeight:700,color:it.hl?"#A16207":DK,marginTop:2}}>{it.v}</div>{it.note&&<div style={{fontSize:6,color:GR,marginTop:1}}>{it.note}</div>}</div>))}</div>

<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6,paddingBottom:4,borderBottom:"2px solid "+LT}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase"}}>Distributors and Brands</div><button onClick={()=>setAddingDist(!addingDist)} style={{background:addingDist?PK:BG,border:"1px solid "+(addingDist?PK:LT),borderRadius:4,padding:"2px 6px",fontSize:8,fontWeight:600,color:addingDist?WH:PK,cursor:"pointer",fontFamily:"'Outfit'"}}>{addingDist?"Cancel":"+ Add Distributor"}</button></div>
{addingDist&&(<div style={{background:BG,borderRadius:8,padding:"10px",border:"1px solid "+LT,marginBottom:10}}>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:6}}>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Distributor</div><select style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}><option>St Charles</option><option>Dawn</option><option value="other">Other (new)</option></select></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Brand name</div><input placeholder="e.g. Ardent Mills" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}/></div>
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:8}}>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Cost / {sel.unit}</div><input placeholder="$0.00" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",textAlign:"right",boxSizing:"border-box"}}/></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>MOQ ({sel.unit})</div><input placeholder="e.g. 25,000" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",textAlign:"right",boxSizing:"border-box"}}/></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Lead time (days)</div><input placeholder="e.g. 14" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",textAlign:"right",boxSizing:"border-box"}}/></div>
</div>
<div style={{display:"flex",gap:4}}><button onClick={()=>setAddingDist(false)} style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"5px 12px",borderRadius:5,fontWeight:700,fontSize:9,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Save Distributor</button></div>
<div style={{marginTop:4,fontSize:7,color:GR,fontStyle:"italic"}}>New distributors/brands expand reorder options. Future forecasting will compare lead times and costs across suppliers.</div>
</div>)}
<table style={{width:"100%",borderCollapse:"collapse",fontSize:10,marginBottom:4}}><thead><tr style={{background:PC}}><th style={th}>Distributor</th><th style={th}>Brand</th><th style={thR}>Cost/{sel.unit}</th><th style={thR}>MOQ</th><th style={thR}>Lead</th><th style={{...thC,width:30}}></th></tr></thead><tbody>{sel.distributors.map((d,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"7px 8px",fontWeight:700}}>{d.dist}</td><td style={{padding:"7px 8px"}}>{d.brand}</td><td style={{padding:"7px 8px",textAlign:"right"}}><span style={{fontWeight:600}}>${d.cost.toFixed(2)}</span></td><td style={{padding:"7px 8px",textAlign:"right"}}>{d.moq>0?d.moq.toLocaleString():"--"}</td><td style={{padding:"7px 8px",textAlign:"right",color:d.lead>=21?"#D97706":GR}}>{d.lead}d</td><td style={{padding:"7px 8px",textAlign:"center"}}><span style={{fontSize:7,color:PK,cursor:"pointer",fontWeight:600}}>edit</span></td></tr>))}</tbody></table>
<div style={{fontSize:7,color:GR,fontStyle:"italic",marginBottom:12}}>Cost, MOQ, and lead time are editable per distributor/brand. Pricing edits require Finance role and trigger audit log. Multiple brands per ingredient enable smarter reorder decisions and future forecasting.</div>

<div style={{background:BG,borderRadius:6,padding:"7px 10px",border:"1px solid "+LT,marginBottom:12,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:9,color:MD}}>Source: Assemblers upload Mar 30 3:42 PM | Sys: {sel.qty.toLocaleString()} {sel.unit}</div><div style={{display:"flex",gap:3,alignItems:"center"}}><input placeholder="Count" style={{width:70,padding:"3px 5px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",textAlign:"right"}}/><button style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"3px 8px",borderRadius:4,fontWeight:700,fontSize:8,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Audit</button></div></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div><div style={{display:"flex",justifyContent:"space-between",marginBottom:3}}><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase"}}>Orders</div><button onClick={()=>setAddingOrder(!addingOrder)} style={{background:addingOrder?PK:BG,border:"1px solid "+(addingOrder?PK:LT),borderRadius:4,padding:"2px 6px",fontSize:8,fontWeight:600,color:addingOrder?WH:PK,cursor:"pointer",fontFamily:"'Outfit'"}}>{addingOrder?"Cancel":"+ Add Order"}</button></div>
{addingOrder&&(<div style={{background:BG,borderRadius:8,padding:"10px",border:"1px solid "+LT,marginBottom:8}}>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:6}}>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Distributor</div><select style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}>{sel.distributors.map((d,di)=>(<option key={di}>{d.dist}</option>))}</select></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Brand</div><select style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}>{sel.distributors.map((d,di)=>(<option key={di}>{d.brand}</option>))}</select></div>
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:6}}>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Qty ({sel.unit})</div><input placeholder="e.g. 25,000" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",textAlign:"right",boxSizing:"border-box"}}/></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Cost/{sel.unit}</div><input placeholder="$0.00" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",textAlign:"right",boxSizing:"border-box"}}/></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Order date</div><input type="date" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}/></div>
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginBottom:8}}>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>Expected delivery</div><input type="date" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}/></div>
<div><div style={{fontSize:7,color:GR,marginBottom:2}}>BOL / Reference</div><input placeholder="BOL-FL-2404" style={{width:"100%",padding:"5px 6px",borderRadius:4,border:"1px solid "+LT,fontSize:9,fontFamily:"'Outfit'",boxSizing:"border-box"}}/></div>
</div>
<div style={{display:"flex",gap:4}}><button onClick={()=>setAddingOrder(false)} style={{background:"linear-gradient(135deg,"+PK+","+PM+")",color:WH,padding:"5px 12px",borderRadius:5,fontWeight:700,fontSize:9,border:"none",cursor:"pointer",fontFamily:"'Outfit'"}}>Save Order</button></div>
<div style={{marginTop:4,fontSize:7,color:GR,fontStyle:"italic"}}>Most orders auto-captured from systems@dirtycookie.com. Use this for manual entry.</div>
</div>)}
{sel.orders.length>0?(<table style={{width:"100%",borderCollapse:"collapse",fontSize:9}}><thead><tr style={{background:PC}}><th style={th}>Date</th><th style={th}>Brand</th><th style={th}>Dist</th><th style={thR}>Qty</th><th style={thR}>Cost</th><th style={thC}>Src</th></tr></thead><tbody>{sel.orders.map((o,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"4px 6px",color:GR}}>{o.d}</td><td style={{padding:"4px 6px",fontWeight:600}}>{o.s}</td><td style={{padding:"4px 6px",color:GR,fontSize:8}}>{o.dist}</td><td style={{padding:"4px 6px",textAlign:"right"}}>{o.q.toLocaleString()}</td><td style={{padding:"4px 6px",textAlign:"right"}}>${o.c.toFixed(2)}</td><td style={{padding:"4px 6px",textAlign:"center"}}><span style={{padding:"1px 3px",borderRadius:3,fontSize:7,fontWeight:600,background:o.src==="email"?"#EDE9FE":"#F3F4F6",color:o.src==="email"?"#6D28D9":GR}}>{o.src==="email"?"A":"M"}</span></td></tr>))}</tbody></table>):(<div style={{fontSize:9,color:GR,fontStyle:"italic"}}>No orders</div>)}</div>
<div><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginBottom:3}}>Used in</div>{sel.usage.length>0?(<table style={{width:"100%",borderCollapse:"collapse",fontSize:9}}><tbody>{sel.usage.map((u,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG}}><td style={{padding:"4px 6px",fontWeight:600}}>{u.p}</td><td style={{padding:"4px 6px",textAlign:"right"}}>{u.q.toLocaleString()} lbs</td></tr>))}</tbody></table>):(<div style={{fontSize:9,color:GR,fontStyle:"italic"}}>No usage data</div>)}{sel.fifo.length>0&&<><div style={{fontSize:8,fontWeight:700,color:PK,textTransform:"uppercase",marginTop:8,marginBottom:3}}>FIFO Lots</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:9}}><tbody>{sel.fifo.map((l,i)=>(<tr key={i} style={{borderBottom:"1px solid "+BG,background:l.exp==="EXPIRED"?"#FEE2E2":"transparent"}}><td style={{padding:"3px 6px",fontFamily:"monospace"}}>{l.lot}</td><td style={{padding:"3px 6px",textAlign:"right"}}>{l.q.toLocaleString()}</td><td style={{padding:"3px 6px",color:l.exp==="EXPIRED"?"#DC2626":GR}}>{l.exp}</td></tr>))}</tbody></table></>}</div></div></div>)}

</div></div></div>);
}
